name: kakoune # you probably want to 'snapcraft register <name>'
base: core18 # Ubuntu 18.04 LTS
version: 'v2019.01.20' # just for humans, typically '1.2+git' or '1.3.2'
license: Unlicense
summary: Modal text editor # 79 char long summary
description: |
  Kakoune is a modal text editor. It is inspired by Vim and similar alternatives,
  but tries to improve the text editing workflow as well as fit better to the
  Unix philosophy. Besides modal editing, two other main concepts are selection
  based editing, and multi-cursor editing. It has an interactive help system,
  and supports many languages. # stolen from Arch wiki
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  kak:
    command: usr/bin/kak
    environment:
      LANGUAGE: "C.UTF-8"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"

parts:
  kakoune:
    plugin: make
    source: .
    source-subdir: src
    make-parameters:
      - PREFIX=/usr
    build-packages:
      - build-essential
      - libncursesw5-dev
      - pkg-config
    stage-packages:
      - libncursesw5
      - libtinfo5
